// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqFQUjNK4pEtAUu24FDMsGr_1GDbvMRII',
    appId: '1:179852023970:web:67cad8cd2aaaed4d5b9ffb',
    messagingSenderId: '179852023970',
    projectId: 'testfirestore-e62d7',
    authDomain: 'testfirestore-e62d7.firebaseapp.com',
    storageBucket: 'testfirestore-e62d7.appspot.com',
    measurementId: 'G-WPXJC933V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9YTPUa9Ywqg5VYmrtMfKbsXeFDEQIug',
    appId: '1:179852023970:android:1dfafe99f09a5ee15b9ffb',
    messagingSenderId: '179852023970',
    projectId: 'testfirestore-e62d7',
    storageBucket: 'testfirestore-e62d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_lgk-2LhwkiXj0c6XAgrZ7PUuK1KR8AQ',
    appId: '1:179852023970:ios:24f886ee493f0fec5b9ffb',
    messagingSenderId: '179852023970',
    projectId: 'testfirestore-e62d7',
    storageBucket: 'testfirestore-e62d7.appspot.com',
    iosBundleId: 'com.example.sampleFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_lgk-2LhwkiXj0c6XAgrZ7PUuK1KR8AQ',
    appId: '1:179852023970:ios:ad9ccc6ad819995a5b9ffb',
    messagingSenderId: '179852023970',
    projectId: 'testfirestore-e62d7',
    storageBucket: 'testfirestore-e62d7.appspot.com',
    iosBundleId: 'com.example.sampleFirestore.RunnerTests',
  );
}
